# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/full_oppo6771-user-10-QP1A.190711.020-7604ad4e2b1328a1-release-keys/oppo6771/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),oppo6771)

endif
